[package]
name = "soulbox"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "High-performance Rust-based AI code execution sandbox"
license = "MIT"
repository = "https://github.com/yourusername/soulbox"
homepage = "https://soulbox.dev"
readme = "README.md"
keywords = ["sandbox", "code-execution", "ai", "grpc", "websocket"]
categories = ["development-tools", "web-programming", "api-bindings"]

[dependencies]
# Async runtime
tokio = { version = "1.35", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Date/Time
chrono = { version = "0.4", features = ["serde"] }

# Environment
dotenvy = "0.15"

# UUID
uuid = { version = "1.6", features = ["v4", "serde"] }

[[bin]]
name = "soulbox"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.dev]
opt-level = 0
debug = true